### ISSUE TITLE
Ошибка в gulpfile.js в параметре options

### ISSUE THREAD

**Issue by xtracode** [brainmurder/InSales-uploader-gulp-test#1]
Скачал последнюю версию, все настроил по инструкции, запустил gulp и получил ошибку:

> gulp download
> gulpfile.js:20
> var InsalesUploader = new insalesUp(options)
>                                     ^
> 
> ReferenceError: options is not defined

Заменил в gulpfile.js var option на var option**s**.
Снова запустил команду gulp и все ок.

Похоже, небольшая опечатка в настройках gulpfile.js.

**Comment by VladimirIvanin** [comment]
Исправил, спасибо!
