### ISSUE TITLE
Не работает(

### ISSUE THREAD

**Issue by Astero81** [brainmurder/InSales-uploader-gulp-test#2]
После переустановки nodejs файлы не обновляются. Таски работают но не происходит обновление. В командной строке пусто. Раньше все работало. Помогите!!!

**Comment by VladimirIvanin** [comment]
Попробуйте удалить папку `node_modules` и  файл `package-lock.json` если есть. После чего установите пакеты заново. 
Важно чтобы установилась версия insales-uploader 0.27.2. Иначе синхронизация ассетов не будет работать.

**Comment by VladimirIvanin** [comment]
Если не поможет, пришлите url магазина

**Comment by Astero81** [comment]
Спасибо сейчас попробую. Кстати, это началось когда я обновил модули в таком порядке
1. npm i -g gulp npm-check-updates
2. ncu
3. ncu -u
4. ncu -a

**Comment by Astero81** [comment]
Не получилось.
1. Удалил node_modules (с помощью rimraf)
2. Удалил файл package-lock.json
3. Запустил npm i

Версия 0.27.2

"dependencies": {
    "gulp": "^3.9.1",
    "gulp-cli": "^1.2.2",
    "gulp-watch": "^4.3.10",
    "promise": "^7.1.1",
    "rifraf": "^2.0.3"
  },
  "devDependencies": {
    "gulp-install": "^1.1.0",
    "insales-uploader": "^0.27.2"
  },

Адрес магазина
http://myshop-gj433.myinsales.ru

**Comment by Astero81** [comment]
Тема не основная
http://myshop-gj433.myinsales.ru/?theme_preview=908401

**Comment by VladimirIvanin** [comment]
А ошибки какие нибудь выдает?
Если да приложите скрин

**Comment by Astero81** [comment]
![screen](https://user-images.githubusercontent.com/22715111/33490741-2ab1c70a-d6c9-11e7-980c-507897226a55.jpg)

**Comment by Astero81** [comment]
Finished 'stream' этого не должно быть?

**Comment by VladimirIvanin** [comment]
Пробуйте запускать задачи раздельно. Сначала gulp download, а после gulp stream. 
С дефолтной посмотрю, что не так

**Comment by VladimirIvanin** [comment]
Finished 'stream' должен быть

**Comment by Astero81** [comment]
Не работает. А новая версия NodeJS никак не влияет? Все началось с этого. До этого все работало((

**Comment by VladimirIvanin** [comment]
Буду разбираться. 
Сейчас у меня работает если убрать из настроек упоминания о фаерфоксе, и запуская таски раздельно.
У меня node v8.9

**Comment by VladimirIvanin** [comment]
![image](https://user-images.githubusercontent.com/15268753/33491319-e6654930-d6ca-11e7-9cb3-58672a11bbe2.png)
Удалил из настроек браузер поумолчанию и ошибок не было. Файлы синхронизируются.

**Comment by Astero81** [comment]
Попробую все переустановить. Владимир, подскажите
Видел такую сборку (стартовый шаблон + gulp)
https://github.com/agragregra/optimizedhtml-start-template
Возможно сделать что то подобное. Я имею ввиду чтобы все стили и js компилировались локально. Как мне известно компиляция Вашей сборки происходит на сервере или это не так?

**Comment by VladimirIvanin** [comment]
scss компилируется на сервере.
Добавление плагинов которые будут что то компилировать или изменять буду пробовать в новой версии аплоадера к которой приступлю в следующем году.

**Comment by Astero81** [comment]
Спасибо за отклик. Будем ждать. Очень нужная вещь.

**Comment by VladimirIvanin** [comment]
у вас в пути к файлу темы есть папка !design. 
Как вариант стоит убрать `!`, может некорректно отрабатывать

**Comment by Astero81** [comment]
Заработало))))) Убрал !.

**Comment by Astero81** [comment]
Владимир, а подскажите еще один вопрос. Если я правильно понял то theme.css - это файл который мы подключаем, в нем есть main.scss который собирает все _file.scss в один + стили плагинов. Т.е. я могу писать все стили и микшины в одном main.scss? И еще файл core.css можно удалить? Т.е. сетку и reset прописать опять же в одном main.scss. Хочу использовать другую сетку) Спасибо

**Comment by VladimirIvanin** [comment]
Все что описали можно сделать, каких то строгих правил нет.
