### ISSUE TITLE
Поддержка подпапок

### ISSUE THREAD

**Issue by ivanthecrazy** [brainmurder/InSales-uploader-gulp-test#3]
Если пытаюсь сделать подпапку в папке media темы, то получаю следующего вида ошибку при push:

[08:29:27] Using gulpfile /mnt/d/projects/gulp-inSales-uploader/gulpfile.js
[08:29:27] Starting 'push'...
/mnt/d/projects/gulp-inSales-uploader/node_modules/insales-uploader/dist/file-system/watch.js:394
        if (err) throw err;
                 ^

Error: EISDIR: illegal operation on a directory, read

Подпапка содержит scss файлы. 

Это в принципе не предусмотрено или я что-то делаю неправильно?

P.S. Без подпапок все работает отлично.

**Comment by VladimirIvanin** [comment]
Спасибо за обратную связь!

Поправил:
https://github.com/insales/insales-uploader/commit/44c76818a8efdccece010f47b11214942be96ec2

Директория и её файлы будут игнорироваться.

Судя по ошибке у вас старая версия insales-uploader. Исправления в версии 1.3.2.

Обратите внимание на новые возможности, insales-uploader стал совместим с gulp плагинами:
![image](https://user-images.githubusercontent.com/15268753/37508613-e6e3869c-2904-11e8-9ebe-94714b7ee100.png)
https://github.com/VladimirIvanin/gulp-inSales-uploader/blob/master/gulpfile.js
