### ISSUE TITLE
Как определить параметры темы

### ISSUE THREAD

**Issue by ivangretsky** [brainmurder/InSales-uploader-gulp-test#5]
Добрый день!

Что значат и как определить параметры темы:
```
  theme:{
    id: '123456',
    root: './my-shop/',
    update: true,
    backup: true,
    assets: true,
    assetsSync: true,
    excludeFiles: [],
    assetsDomain: 'https://assets.insales.ru'
  },
```
Есть ли подробное описание этих и других настроек в options.js?

**Comment by VladimirIvanin** [comment]
Добрый день!
Описание настроек:
https://insales.github.io/insales-uploader/#options
Как получить настройки можно посмотреть на видео.
https://www.youtube.com/watch?v=ImFlI1sUp5U
